# Generated by Django 4.1.4 on 2022-12-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=60)),
                ('image_link', models.CharField(max_length=255)),
                ('post', models.TextField(max_length=2000)),
            ],
        ),
    ]
